language: ruby
rvm:
  - 2.0.0
before_install:
  - "gem install bundler --version 1.3.0 --no-ri --no-rdoc"
before_script:
  - "ruby lib/initial_setup.rb ../.travis_setup"
  - psql -c 'create database rely_test;' -U postgres
  - "bundle exec rake db:migrate"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
